# Global options
AllCops:
  DisplayCopNames: true

Metrics/AbcSize:
  Max: 60

Metrics/CyclomaticComplexity:
  Max: 15

Metrics/LineLength:
  # This will disable the rule completely, regardless what other options you put
  Enabled: true
  # Change the default 80 chars limit value
  Max: 120

Metrics/MethodLength:
  # This cop checks if the length of a method exceeds some maximum value
  Enabled: true
  # Change the default 10 lines limit value
  Max: 50

# Allow classes longer than 100 lines of code
ClassLength:
  Max: 250

Naming/UncommunicativeMethodParamName:
  Enabled: false

Lint/UnneededCopDisableDirective:
  Enabled: false

Metrics/PerceivedComplexity:
  Max: 10

Metrics/ParameterLists:
  Max: 6
